# ==============================================================================
# Production Profile Properties
# ==============================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Prod settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# CORS Allowed Origin
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}
